---
ec2_name_prefix: Test-Juniper
ec2_region: ap-southeast-2
ec2_wait: yes
#need to circle back and fix this for teardown - sean
ec2_az: "{{ec2_region}}a"
ec2_subnet: "172.16.0.0/16"
ec2_subnet2: "172.17.0.0/16"
ec2_vpc_subnet_id: "subnet-09fab7d8a13f32ce6"
ec2_vpc_subnet_id2: "subnet-0da338d16352f33bc"
ec2_security_group: "Cisco-insecure_all"
ec2_security_group2: "Cisco-insecure_all2"
student_total: 1
ec2_vpc_id: vpc-0b00c8cde80b8967d
ec2_vpc_id2: vpc-0ef72dd9bc56f015d



networking: false
ssh_port: 22

ec2_lab_node_types_networking:
  tjnp3: junos-byol
  tjnp4: junos-byol


# Instance types used for lab configurations
ec2_instance_types:
  junos-byol:
    owners: 679593333241
    size: m4.xlarge
    os_type: linux
    disk_space: 32
    architecture: x86_64
    filter: "vmx-nested-17.4R1-S2.2-3-ami*"
    os: junos

# Login names used for SSH connections. These are baked in to the AMIs.
ec2_login_names:
  junos-byol: jnpr